### ISSUE TITLE
Failed to load Profile from Server

### ISSUE THREAD

**Issue by Vezuure** [MerchV/Get-iOS-UDID#1]
im getting an Error saying cant download the profile because there no connection to the server.
What can i do to fix this ? couldnt find any solutions

**Comment by MerchV** [comment]
Have you made the 3 edits in these 3 files on these lines?

enroll.mobileconfig line 8
done.php line 75
submit.php line 3

**Comment by Vezuure** [comment]
Yeah i did. 
what kind of server and configuration are u using ?

**Comment by MerchV** [comment]
The server is a plain shared web host. It's not running anything special. It's just running an Apache web server and PHP. All of the files need to be publicly visible from the web.

I haven't looked at this code in over a year so I don't immediately remember how everything works.

I just tried it myself right now and it works for me. I have it set up at http://merchv.com/register-your-ipad/

I can't remember if you need to have an SSL certificate on the web host so that all the links are HTTPS. Maybe you do.

**Comment by Vezuure** [comment]
i do have a ssl and all the urls are forced to https

**Comment by Vezuure** [comment]
i have a Ubuntu 14.04 LAMP Server provided by DigitalOcean 
with an SSL provided by CertBot (https://certbot.eff.org/#ubuntutyakkety-apache)
and i got an 1 Year Developer Account by Apple.

i made a Private Application which can be downloaded over Web (with valid SSL) if the UDID is registered in the Apple Dev Portal.

Thats why i need a implemented UDID Grabber.
but it seems reject the Connection if i try to download the Profile.
i changed all the infos you listed and it works until i try to install it and then it says "Could not download from the Server"

i even tried to sign it with an ssl but then it bricks the mobileconfig file.

i also tried to change the PayloadUUID with a generated one by using the Command uuidgen in Terminal or by modifying the PayloadIdentifier but that also wont work.

i hope u can help me :)

**Comment by MerchV** [comment]
Can you send me a link so I can try it on my iPhone or view the source code? You can e-mail me at merchv@gmail.com if you don't want to paste it here.

**Comment by Vezuure** [comment]
https://vezuure.me

**Comment by MerchV** [comment]
OK, I also see "Profile Installation Failed – A connection to the server could not be established" when I try to install the profile. I am going to look through the source files.

**Comment by MerchV** [comment]
Can you show me what you have on line 75 of done.php?

The original line was:

header('Location: https://YOUR-DOMAIN.com/YOUR-PATH/complete?'.$params);

**Comment by Vezuure** [comment]
header('Location: https://vezuure.me/complete?'.$params);

**Comment by MerchV** [comment]
I want you to try something. I notice you put the files at the root directory. I want you to try putting everything into a subdirectory. For example, instead of:

http://vezuure.me/done.php
http://vezuure.me/enroll.mobileconfig
http://vezuure.me/index.html
http://vezuure.me/register-button@2x.png
http://vezuure.me/complete/finished.html
http://vezuure.me/complete/index.php
http://vezuure.me/complete/submit.php

put it all into a subdirectory, such as:

http://vezuure.me/temp/done.php
http://vezuure.me/temp/enroll.mobileconfig
http://vezuure.me/temp/index.html
http://vezuure.me/temp/register-button@2x.png
http://vezuure.me/temp/complete/finished.html
http://vezuure.me/temp/complete/index.php
http://vezuure.me/temp/complete/submit.php

**Comment by Vezuure** [comment]
done subfolder "temp"
and also edited done.php and enroll.mobileconfig to match the new url

**Comment by Vezuure** [comment]
After doing some research i compared your domain with mine and i figured out that you are using a comodo cert SSL and im using a free one by letsencrypt and then i browsed trough apples forums and found this https://support.apple.com/en-us/HT207177 could this be the problem ?

**Comment by Vezuure** [comment]
ffs i tried to reinstall a fresh Ubuntu 16.04 Web Server with Apache2 and PHP and then i installed one of my paid Comodo SSL certificates and i was in hope that it would work now, but still no fix.
got now a new server ip and login credientals.
if you still need access hmu.

**Comment by Vezuure** [comment]
i was able even able to Sign the profile but still cant download it

**Comment by Vezuure** [comment]
FIXED.
It's an PHP7.0 related issue "Uncaught Error: Call to undefined function xml_parser_create e()"
Solution: sudo apt-get install php-xml && apt-get install php7.0-xml
Works now.

**Comment by MerchV** [comment]
Thanks for helping me solve the issue.

**Comment by Vezuure** [comment]
Should next time first check the server errror log file 🤔

**Comment by MerchV** [comment]
I registered my iPhone with your script at vezuure.me to see that it works (=
